// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using debil_be.Data;
using debil_be.Entities;

#nullable disable

namespace debil_be.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("debil_be.Entities.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlueprintId")
                        .HasColumnType("uuid");

                    b.Property<string>("BlueprintName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FileStorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<List<ColumnMeta>>("InputColumns")
                        .HasColumnType("jsonb");

                    b.Property<List<OutputColumnMeta>>("OutputColumns")
                        .HasColumnType("jsonb");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("Status");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("debil_be.Entities.AnalysisRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, object>>("InputData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, object>>("OutputData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("AnalysisId", "RowIndex")
                        .IsUnique();

                    b.ToTable("AnalysisRows");
                });

            modelBuilder.Entity("debil_be.Entities.Blueprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Dictionary<string, string>>("DataStructure")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("Blueprints");
                });

            modelBuilder.Entity("debil_be.Entities.BlueprintTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlueprintId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Format")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Instruction")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Question")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<List<TaskValue>>("Values")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.ToTable("BlueprintTasks");
                });

            modelBuilder.Entity("debil_be.Entities.Analysis", b =>
                {
                    b.HasOne("debil_be.Entities.Blueprint", "Blueprint")
                        .WithMany("Analyses")
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blueprint");
                });

            modelBuilder.Entity("debil_be.Entities.AnalysisRow", b =>
                {
                    b.HasOne("debil_be.Entities.Analysis", "Analysis")
                        .WithMany("Rows")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("debil_be.Entities.BlueprintTask", b =>
                {
                    b.HasOne("debil_be.Entities.Blueprint", "Blueprint")
                        .WithMany("Tasks")
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blueprint");
                });

            modelBuilder.Entity("debil_be.Entities.Analysis", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("debil_be.Entities.Blueprint", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
