// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReviewInsights.Api.Data;
using ReviewInsights.Api.Domain.ValueObjects;

#nullable disable

namespace ReviewInsights.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReviewInsights.Api.Domain.Entities.FileUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnalyzedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("analyzed_records");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_key");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer")
                        .HasColumnName("total_records");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_file_uploads_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_file_uploads_status");

                    b.ToTable("file_uploads", (string)null);
                });

            modelBuilder.Entity("ReviewInsights.Api.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<ReportFilters>("Filters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filters");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<List<ReportInsight>>("Insights")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("insights");

                    b.Property<ReportScope>("Scope")
                        .HasColumnType("jsonb")
                        .HasColumnName("scope");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<List<ReportSuggestion>>("Suggestions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggestions");

                    b.Property<ReportSummary>("Summary")
                        .HasColumnType("jsonb")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer")
                        .HasColumnName("total_records");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt")
                        .HasDatabaseName("ix_reports_generated_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_reports_status");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("ReviewInsights.Api.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at");

                    b.Property<List<AspectSentiment>>("AspectSentiments")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("aspect_sentiments");

                    b.PrimitiveCollection<string>("ChurnCauses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("churn_causes");

                    b.Property<int?>("ChurnProbability")
                        .HasColumnType("integer")
                        .HasColumnName("churn_probability");

                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("class_name");

                    b.Property<int>("ClothingId")
                        .HasColumnType("integer")
                        .HasColumnName("clothing_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department_name");

                    b.Property<string>("DivisionName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("division_name");

                    b.Property<int?>("OverallSentiment")
                        .HasColumnType("integer")
                        .HasColumnName("overall_sentiment");

                    b.Property<int>("PositiveFeedbackCount")
                        .HasColumnType("integer")
                        .HasColumnName("positive_feedback_count");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<bool>("RecommendedInd")
                        .HasColumnType("boolean")
                        .HasColumnName("recommended_ind");

                    b.Property<string>("ReviewText")
                        .HasColumnType("text")
                        .HasColumnName("review_text");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_id");

                    b.HasKey("Id");

                    b.HasIndex("ClothingId")
                        .HasDatabaseName("ix_reviews_clothing_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_reviews_created_at");

                    b.HasIndex("DepartmentName")
                        .HasDatabaseName("ix_reviews_department");

                    b.HasIndex("OverallSentiment")
                        .HasDatabaseName("ix_reviews_sentiment");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_reviews_priority");

                    b.HasIndex("Rating")
                        .HasDatabaseName("ix_reviews_rating");

                    b.HasIndex("UploadId")
                        .HasDatabaseName("ix_reviews_upload_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("ReviewInsights.Api.Domain.Entities.Review", b =>
                {
                    b.HasOne("ReviewInsights.Api.Domain.Entities.FileUpload", "Upload")
                        .WithMany("Reviews")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("ReviewInsights.Api.Domain.Entities.FileUpload", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
